name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm install

      - name: Configurar identidad de Git
        run: |
          git config --global user.email "grupo90pr@gmail.com"
          git config --global user.name "GitHub Actions"

      - name: Desplegar usando gh-pages
        run: npm run deploy
        env:
          CI: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
